apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-job
spec:
  schedule: "*/2 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure  # Add or correct this line
          containers:
            - name: backup-job
              image: backuper:latest
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: my-volume
                  mountPath: /app/backupfolder
                - name: google-drive-credentials
                  mountPath: /app/google_drive_credentials
          volumes:
            - name: my-volume
              persistentVolumeClaim:
                claimName: my-pvc
            - name: google-drive-credentials
              secret:
                secretName: google-drive-credentials
