apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-job
spec:
  schedule: "*/2 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup-job
              image: backuper:latest
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: my-volume
                  mountPath: /app/backupfolder
          volumes:
            - name: my-volume
              persistentVolumeClaim:
                claimName: my-pvc
          restartPolicy: OnFailure