apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: backuper:latest
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: data-volume
          mountPath: /app/backupfolder
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: my-pvc
  restartPolicy: OnFailure
